console.log("components");

import burger from "./components/burger";
import sizesCalc from "./components/sizesCalc";
import sizesPopup from "./components/sizesPopup";
import processSwiper from "./components/processSwiper";
import ideasSwiper from "./components/ideasSwiper";
import stretchSwiper from "./components/stretchSwiper";
import coveragesSwiper from "./components/coveragesSwiper";
import framesSwiper from "./components/framesSwiper";
import ourWorksSwiper from "./components/ourWorksSwiper";
import calcFileLabel from "./components/calcFileLabel";
import calcDemo from "./components/calcDemo";
import calcFakeSelect from "./components/calcFakeSelect";
import "./components/summary";
import calcDemoShow from "./components/calcDemoShow";
import calcLogic from "./components/calcLogic";
import calcformShipment from "./components/calcformShipment";
import designAdditionalCounter from "./components/designAdditionalCounter";
import "./components/sizesSwiper";
import framesRandomiser from "./components/framesRansomiser";
